services:
  postgres:
    image: postgres:16-alpine
    container_name: raisa_diary_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raisa_diary
    ports:
      - "5432:5432"
    volumes:
      - raisa_pg_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  raisa_pg_data:
